#!/usr/bin/env python3
"""
mid2glsl.py -- convert a Standard MIDI File into a Shadertoy sound shader.
No dependencies. SMF format 0/1, running status, tempo, multi-track.

Two emit modes:
  grains (default) : each note -> summed additive grain. Naturally POLYPHONIC,
                     no voice-splitting. Drawbar-organ instrument (after the
                     'good organ' additive shader) + compact AD envelope.
  macro            : tekf-style N()/L() delta-tick track fns (monophonic,
                     voice-split). Kept for the scan-based approach.

Usage:  python3 mid2glsl.py in.mid out.glsl [--bpm N] [--mode grains|macro]
"""
import sys, struct

# ----------------------------------------------------------------- SMF parse
def _varlen(d, i):
    v = 0
    while True:
        b = d[i]; i += 1
        v = (v << 7) | (b & 0x7f)
        if not (b & 0x80): break
    return v, i

def parse_midi(path):
    d = open(path, "rb").read()
    assert d[:4] == b"MThd", "not a MIDI file"
    fmt, ntrk, div = struct.unpack(">HHH", d[8:14])
    tpq = div if div < 0x8000 else 480
    pos, tempo, tracks = 14, 500000, []
    for _ in range(ntrk):
        assert d[pos:pos+4] == b"MTrk"
        length = struct.unpack(">I", d[pos+4:pos+8])[0]
        pos += 8; end = pos + length
        t = 0; status = 0; on = {}; notes = []
        while pos < end:
            dt, pos = _varlen(d, pos); t += dt
            b = d[pos]
            if b & 0x80: status = b; pos += 1
            ev = status & 0xf0
            if status == 0xff:
                mtype = d[pos]; pos += 1
                mlen, pos = _varlen(d, pos)
                if mtype == 0x51:
                    tempo = struct.unpack(">I", b"\x00"+d[pos:pos+3])[0]
                pos += mlen
            elif status in (0xf0, 0xf7):
                slen, pos = _varlen(d, pos); pos += slen
            elif ev in (0x90, 0x80):
                note, vel = d[pos], d[pos+1]; pos += 2
                if ev == 0x90 and vel > 0:
                    on.setdefault(note, []).append((t, vel))
                else:
                    if on.get(note):
                        s, v = on[note].pop(0); notes.append((s, t-s, note, v))
            elif ev in (0xc0, 0xd0): pos += 1
            else:                    pos += 2
        if notes: tracks.append(sorted(notes))
    return tpq, tempo, tracks

def ntof(n): return 440.0 * 2.0 ** ((n - 69) / 12.0)

# ============================================================ GRAINS (default)
GRAIN_TEMPLATE = """// auto-generated by mid2glsl.py (grains) -- {n} notes, polyphonic
#define T 6.28318530718

float w(float f, float x){{ return sin(x*f*T); }}

// compact AD envelope: linear attack vs sqrt(duration)-scaled exp decay
float env(float x, float start, float dur, float atk){{
    float dt = max(0.0, x-start);
    return min(dt/atk, exp(2.0*(atk-dt)/sqrt(dur)));
}}

// drawbar organ grain (harmonics 1,2,4,6 -- hollow Hammond color)
float g(float f, float start, float dur, float x){{
    float s = w(f,x)*0.15 + w(f*2.0,x)*0.20 + w(f*4.0,x)*0.075 + w(f*6.0,x)*0.015;
    return s * env(x, start, dur, 0.004);
}}

float music(float x){{
    float s = 0.0;
{body}
    return s;
}}

// ── master soft-knee limiter (ported 1:1 from MOD2GLSL's mod_player.py) ──
// over=max(|x|-T,0); reduced=HEAD*over/(over+HEAD); y=sign*(min(|x|,T)+reduced)
// T=0.85 knee: bit-perfect below it; the summed voices then APPROACH 1.0
// smoothly instead of hard-clipping (the many-voices distortion).
float softLimit1(float x){{
    const float T=0.85, HEAD=1.0-T;
    float ax=abs(x), over=max(ax-T,0.0);
    return sign(x)*(min(ax,T) + HEAD*over/(over+HEAD));
}}

vec2 mainSound(int samp, float time){{
    float x = time;                                   // tempo baked into grains
    float m = softLimit1(music(x)*{gain:.3f});
    return vec2(m * smoothstep(0.0, 0.3, time));
}}
"""

def build_grains(tpq, tempo, tracks, bpm=None):
    us_per_q = 60_000_000 / bpm if bpm else tempo
    tps = tpq * (1_000_000 / us_per_q)
    notes = sorted(n for trk in tracks for n in trk)          # flatten all voices
    calls = [f"g({ntof(n):.3f},{s/tps:.4f},{max(dur/tps,0.02):.4f},x)"
             for (s, dur, n, v) in notes]
    lines, chunk = [], 10
    for i in range(0, len(calls), chunk):
        lines.append("    s += " + " + ".join(calls[i:i+chunk]) + ";")
    body = "\n".join(lines)
    gain = 0.45
    return GRAIN_TEMPLATE.format(n=len(notes), body=body, gain=gain)

# ============================================================ MACRO (scan)
def split_voices(notes):
    voices = []
    for s, dur, n, v in notes:
        for vc in voices:
            if vc[-1][0] + vc[-1][1] <= s: vc.append((s, dur, n, v)); break
        else: voices.append([(s, dur, n, v)])
    return voices

def emit_track(name, voice):
    out, t = [], 0
    for i, (s, dur, n, _) in enumerate(voice):
        delta = s - t
        nxt = voice[i+1][0] if i+1 < len(voice) else None
        out.append(f"N({delta},{n})" if (nxt is not None and s+dur >= nxt)
                   else f"L({delta},{n},{dur})")
        t = s
    return (f"vec2 {name}(float x){{ vec2 r=vec2(-1.0); float t=0.0;\n"
            f"    {''.join(out)}\n    return r; }}")

MACRO_TEMPLATE = """// auto-generated by mid2glsl.py (macro) -- {nv} voices, {tps:.1f} ticks/s
#define TAU 6.28318530718
#define N(D,V) t+=float(D); if(x>t) r=vec2(V,t);
#define L(D,V,X) t+=float(D); if((x>t)&&(x<(t+float(X)))) r=vec2(V,t);

float NoteToHz(float n){{ return 440.0*exp2((n-69.0)/12.0); }}
float fbsin(float p,float fb){{ float y=sin(p); y=sin(p+fb*y); y=sin(p+fb*y); return y; }}
float env(float t,float a,float dec){{ return (1.0-exp(-t/max(a,1e-4)))*exp2(-t*(5.0/dec)); }}

float voice(vec2 ft){{
    float f=ft.x, t=ft.y; if(f<=0.0) return 0.0;
    float ph=TAU*f*t; float I=2.4*exp2(-t*4.0)+0.8; float m=I*fbsin(ph,0.5);
    return (sin(ph+m)+sin(ph*1.004+m))*0.5*env(t,0.012,0.55);
}}

{tracks}

const float kTPS = {tps:.6f};
vec2 note(vec2 midi, float now){{
    if(midi.x < 0.0) return vec2(0.0, 1e3);
    return vec2(NoteToHz(midi.x), max(now-midi.y,0.0)/kTPS); }}

// ── master soft-knee limiter (ported 1:1 from MOD2GLSL's mod_player.py) ──
// T=0.85 knee: bit-perfect below it; summed voices approach 1.0 smoothly
// instead of hard-clipping (the many-voices distortion).
float softLimit1(float x){{
    const float T=0.85, HEAD=1.0-T;
    float ax=abs(x), over=max(ax-T,0.0);
    return sign(x)*(min(ax,T) + HEAD*over/(over+HEAD));
}}

float PlayMidi(float time){{
    if(time<0.0) return 0.0; float x=time*kTPS; float r=0.0;
{plays}
    return softLimit1(r*{gain:.3f}); }}

vec2 mainSound(int samp, float time){{
    return vec2(PlayMidi(time)*smoothstep(0.0,0.4,time)); }}
"""

def build_macro(tpq, tempo, tracks, bpm=None):
    us_per_q = 60_000_000 / bpm if bpm else tempo
    tps = tpq * (1_000_000 / us_per_q)
    voices = [vc for trk in tracks for vc in split_voices(trk)]
    fns   = [emit_track(f"Trk{i}", vc) for i, vc in enumerate(voices)]
    plays = "\n".join(f"    r += voice(note(Trk{i}(x), x));" for i in range(len(voices)))
    gain = 1.0 / max(len(voices), 1) ** 0.5
    return MACRO_TEMPLATE.format(nv=len(voices), tps=tps,
                                 tracks="\n\n".join(fns), plays=plays, gain=gain)

# ============================================================ BUFFER (block-indexed)
# Emits the packed data block a block-indexed player (e.g. the modal-piano engine)
# consumes. Layout inferred strictly from that decoder's reads:
#   midiOM[i] = onTick | (meta<<16);  meta = noteOffset(7b) | (vel7<<7)
#   midiDur[i>>1] packs two 16b durations;  midiSC[b] = start(16b) | count(16b)
SHARD = 2048   # max elements per const array (lower if a driver still rejects it)

def emit_sharded(name, vals, shard=SHARD):
    """Split a uint list into <=shard-sized const uvec4 arrays + a runtime accessor.
    4 uints are packed per uvec4 element — which is what the GPU / ANGLE const-
    storage budget actually counts — so this quarters the declared slot count
    (e.g. uint[2048] -> uvec4[512]) and helps weak cards fit. uvec4 (not ivec4)
    because the data is unsigned: each lane reads straight back as a uint, with no
    reliance on uint(negativeInt) wrap for values >= 2^31 (long note durations)."""
    if not vals:
        vals = [0]
    chunks = [vals[i:i+shard] for i in range(0, len(vals), shard)]
    lines = []
    for c, ch in enumerate(chunks):
        packed = []
        for i in range(0, len(ch), 4):
            g = (ch[i:i+4] + [0, 0, 0, 0])[:4]         # zero-pad the final group to 4
            packed.append("uvec4(%du,%du,%du,%du)" % (g[0]&0xFFFFFFFF, g[1]&0xFFFFFFFF, g[2]&0xFFFFFFFF, g[3]&0xFFFFFFFF))
        lines.append(f"const uvec4 {name}{c}[{len(packed)}] = uvec4[{len(packed)}]({','.join(packed)});")
    acc = [f"uint {name}(uint i){{"]
    for c, ch in enumerate(chunks):
        rd = f"{name}{c}[i>>2u][int(i&3u)]"            # uvec4 element + lane -> uint
        if c == 0:
            acc.append(f"  if(i<{len(ch)}u) return {rd};")
        else:
            acc.append(f"  i-={len(chunks[c-1])}u; if(i<{len(ch)}u) return {rd};")
    acc.append("  return 0u;\n}")
    return "\n".join(lines) + "\n" + "\n".join(acc)

def build_buffer(tpq, tempo, tracks, bpm=None, Q=256, shift=6, pad_sec=1.2, sr=44100.0):
    us_per_q = 60_000_000/bpm if bpm else tempo
    sec_per_tick = us_per_q/1e6/tpq                      # seconds per source MIDI tick
    qSec = Q/sr                                          # seconds per output tick
    c16 = lambda x: min(int(x), 0xFFFF)
    notes = []
    for trk in tracks:
        for (s, dur, n, v) in trk:
            onT = round(s*sec_per_tick/qSec)
            dT  = max(1, round(dur*sec_per_tick/qSec))
            notes.append((onT, dT, n, v))
    notes.sort(key=lambda e: e[0])
    N = len(notes)
    note_min = min(n for _, _, n, _ in notes)
    blk = 1 << shift
    end_tick = c16(max(o+d for o, d, _, _ in notes) + 1)
    nblocks  = (end_tick + blk - 1)//blk

    OM, DUR = [], []
    for onT, dT, n, v in notes:
        meta = ((n-note_min) & 0x7F) | ((max(0, min(127, v))) << 7)
        OM.append(c16(onT) | (meta << 16))
        DUR.append(c16(dT))
    if len(DUR) % 2: DUR.append(0)
    DURW = [DUR[i] | (DUR[i+1] << 16) for i in range(0, len(DUR), 2)]

    SC, idx = [], 0
    for b in range(nblocks):
        start, cnt = idx, 0
        while idx < N and (notes[idx][0] >> shift) == b:
            idx += 1; cnt += 1
        SC.append((start & 0xFFFF) | (min(cnt, 0xFFFF) << 16))

    max_dur   = max(d for _, d, _, _ in notes)
    pad_ticks = round(pad_sec/qSec)
    lookback  = (max_dur + pad_ticks)//blk + 2

    def arr(name, vals):
        body = ",".join(f"{v}u" for v in vals)
        return f"const uint {name}[{len(vals)}] = uint[{len(vals)}]({body});"

    defs = "\n".join([
        "// --- paste into the Common tab; drives the block-indexed player ---",
        "#define MIDI_SAMPLE_RATE 44100.0",
        f"#define MIDI_TIME_Q_SAMPLES {Q}",
        f"#define MIDI_END_TICK {end_tick}u",
        f"#define MIDI_BLOCK_SHIFT_TICKS {shift}u",
        f"#define MIDI_BLOCK_COUNT {nblocks}u",
        f"#define MIDI_SEG_COUNT {N}u",
        f"#define MIDI_LOOKBACK_BLOCKS {lookback}u",
        f"#define MIDI_NOTE_MIN {note_min}",
        "#define MIDI_VEL_BITS 7u", ""])
    return (defs + "\n" + emit_sharded("midiOM", OM) + "\n\n"
            + emit_sharded("midiDur", DURW) + "\n\n" + emit_sharded("midiSC", SC) + "\n"), notes, dict(
            Q=Q, shift=shift, blk=blk, nblocks=nblocks, lookback=lookback,
            note_min=note_min, end_tick=end_tick, N=N)

PLAYER_CODE = r"""
// ---- self-contained block-indexed player (brass) ------------------
#define TAU 6.28318530718
float NoteToHz(int n){ return 440.0*exp2((float(n)-69.0)/12.0); }
uint  onTick(uint i){ return midiOM(i)&0xFFFFu; }
uint  meta16(uint i){ return midiOM(i)>>16; }
uint  durTick(uint i){ uint w=midiDur(i>>1u); return ((i&1u)==0u)?(w&0xFFFFu):(w>>16); }
int   metaNote(uint m){ return MIDI_NOTE_MIN+int(m&0x7Fu); }
float metaVel(uint m){ return float((m>>7)&127u)/127.0; }

float fbsin(float p,float fb){ float y=sin(p); y=sin(p+fb*y); y=sin(p+fb*y); return y; }

// ── master soft-knee limiter (ported 1:1 from MOD2GLSL's mod_player.py) ──
// T=0.85 knee: bit-perfect below it; the summed voices approach 1.0 smoothly
// instead of saturating from the first sample like the old always-on tanh.
vec2 softLimit(vec2 x){
    const float T=0.85, HEAD=1.0-T;
    vec2 ax=abs(x), over=max(ax-T,vec2(0.0));
    return sign(x)*(min(ax,vec2(T)) + HEAD*over/(over+HEAD));
}

// FM brass voice: freq, seconds since onset, velocity
float voice(float f, float ageOn, float vel){
    float ph = TAU*f*ageOn;
    float I  = (1.0+2.4*vel)*exp2(-ageOn*3.5) + 0.6;
    float m  = I*fbsin(ph, 0.5);
    float dec= 0.55 + 0.45*exp2(-ageOn*0.7);            // gentle decay so holds don't drone
    return (sin(ph+m)+sin(ph*1.004+m))*0.5*dec;
}

// ── volume ADSR envelope + opt-in comb reverb ── tune via these #defines / -D ─
#ifndef ENV_ATTACK
#define ENV_ATTACK  0.02      // s: onset swell (raise for softer opening, e.g. 0.05)
#endif
#ifndef ENV_DECAY
#define ENV_DECAY   0.09      // s: peak -> sustain
#endif
#ifndef ENV_SUSTAIN
#define ENV_SUSTAIN 0.72      // 0..1: held level
#endif
#ifndef ENV_RELEASE
#define ENV_RELEASE 0.18      // s: note-off decay
#endif
#ifndef USE_REVERB
#define USE_REVERB 1          // reverb ON by default; pass --no-reverb (or set 0) to disable
#endif
#ifndef REVERB_MIX
#define REVERB_MIX 0.42       // wet amount
#endif
#define REV_T1 0.017
#define REV_T2 0.026
#define REV_T3 0.037
#define REV_T4 0.051
#define REV_T5 0.068
#ifndef MASTER_GAIN
#define MASTER_GAIN 0.45      // overall level (raise if too quiet)
#endif
#ifndef POLY_COMP
#define POLY_COMP   0.5       // polyphony compensation: >0 tames dense chords, 0 = off
#endif

// attack->decay->sustain level at `age` s since onset (release added at call site)
float envLvl(float age){
    if(age < ENV_ATTACK) return smoothstep(0.0, ENV_ATTACK, age);   // S-curve swell, no hard corner
    float d = age - ENV_ATTACK;
    if(d < ENV_DECAY)    return mix(1.0, ENV_SUSTAIN, d/ENV_DECAY);
    return ENV_SUSTAIN;
}
// a note's fully-enveloped voice output at `age` s since onset (0 before onset)
float noteSig(float f, float held, float vel, float age){
    if(age < 0.0) return 0.0;
    float e = (age < held) ? envLvl(age) : envLvl(held)*exp(-(age-held)/ENV_RELEASE);
    return voice(f, age, vel) * e * vel;
}

vec2 mainSound(int samp, float timeNow){
    float SR   = MIDI_SAMPLE_RATE;
    float qSec = float(MIDI_TIME_Q_SAMPLES)/SR;
    float tPhase = float(samp)/SR;
    float songLen= float(MIDI_END_TICK)*qSec;
    float tEvent = mod(tPhase, songLen);

    uint T = uint(floor(tEvent/qSec + 0.5));
    T = min(T, MIDI_END_TICK-1u);
    uint b = T >> MIDI_BLOCK_SHIFT_TICKS;
    if(b >= MIDI_BLOCK_COUNT) return vec2(0.0);
    uint padT = uint(1.2/qSec + 0.5);

    float L=0.0, R=0.0, nrg=0.0;
    for(uint j=0u; j<(samp<0 ? 99999u : MIDI_LOOKBACK_BLOCKS); j++){  // de-unroll: samp<0 is always false at runtime but ANGLE can't fold it → keeps this a runtime loop (1 copy) instead of unrolling the note-scan body MIDI_LOOKBACK_BLOCKS× → smaller shader, faster compile, no private-var CONTEXT_LOST on weak GPUs
        if(b < j) break;
        uint bi=b-j, sc=midiSC(bi), start=sc&0xFFFFu, count=sc>>16;
        for(uint k=0u; k<count; k++){
            uint si=start+k; if(si>=MIDI_SEG_COUNT) break;
            uint onT=onTick(si); if(T<onT) continue;
            uint dT=durTick(si), offT=onT+dT;
            if(T > offT+padT) continue;

            uint m=meta16(si); int nn=metaNote(m); float vel=metaVel(m);
            float onSec=float(onT)*qSec, offSec=float(offT)*qSec;
            float ageOn=max(0.0, tEvent-onSec);
            float held =float(dT)*qSec;
            float ageOff=(tEvent>offSec)?(tEvent-offSec):0.0;

            // volume ADSR: attack->decay->sustain while held, exp release from note-off level
            float f = NoteToHz(nn);
            float e = (tEvent<offSec) ? envLvl(ageOn) : envLvl(held)*exp(-ageOff/ENV_RELEASE);
            if(e < 0.0004) continue;
            float s = voice(f, ageOn, vel)*e*vel;
#if USE_REVERB
            // comb reverb via linearity: each note + a few decaying, time-delayed
            // copies of itself (reverb(mix)=sum reverb(note); stateless, no re-scan)
            s += REVERB_MIX*( 0.34*noteSig(f,held,vel,ageOn-REV_T1)
                            + 0.27*noteSig(f,held,vel,ageOn-REV_T2)
                            + 0.21*noteSig(f,held,vel,ageOn-REV_T3)
                            + 0.16*noteSig(f,held,vel,ageOn-REV_T4)
                            + 0.12*noteSig(f,held,vel,ageOn-REV_T5) );
#endif
            float pan = clamp((float(nn)-72.0)/36.0,-1.0,1.0)*0.30;
            nrg += e*vel;   // sum of voice loudnesses, for polyphony normalization
            L += s*(0.5-pan*0.5); R += s*(0.5+pan*0.5);
        }
    }
    // polyphony-aware master gain — DYNAMIC: nrg is the live summed voice energy,
    // recomputed every sample, so g rides up/down with the real-time polyphony
    // (chord hits -> g drops, chord releases -> g rises). sqrt() soft-knee: unity
    // when sparse, ~1/energy rolloff when dense, gliding smoothly across the knee
    // instead of stepping. POLY_COMP sets the knee (higher = tames sooner; 0 = off).
    float lvl = nrg*POLY_COMP;
    float g   = MASTER_GAIN * inversesqrt(1.0 + lvl*lvl);
    vec2 lr = softLimit(vec2(L,R)*g);
    return lr * smoothstep(0.0, 0.4, tPhase);
}
"""

def build_player(tpq, tempo, tracks, bpm=None):
    return build_buffer(tpq, tempo, tracks, bpm)[0] + PLAYER_CODE

def build_shader(tpq, tempo, tracks, bpm=None, mode="grains"):
    if mode == "buffer": return build_buffer(tpq, tempo, tracks, bpm)[0]
    if mode == "player": return build_player(tpq, tempo, tracks, bpm)
    return (build_grains if mode == "grains" else build_macro)(tpq, tempo, tracks, bpm)

# ------------------------------------------------------------ minimal writer
def write_midi(path, tracks, tpq=480, tempo=500000):
    def vlq(n):
        out = bytearray([n & 0x7f]); n >>= 7
        while n: out.insert(0, (n & 0x7f) | 0x80); n >>= 7
        return bytes(out)
    chunks = b""
    for ti, notes in enumerate(tracks):
        ev = []
        if ti == 0: ev.append((0, b"\xff\x51\x03" + struct.pack(">I", tempo)[1:]))
        for s, dur, n, v in notes:
            ev.append((s, bytes([0x90, n, v]))); ev.append((s+dur, bytes([0x80, n, 0])))
        ev.sort(key=lambda e: e[0])
        data, last = b"", 0
        for tick, msg in ev: data += vlq(tick-last) + msg; last = tick
        data += vlq(0) + b"\xff\x2f\x00"
        chunks += b"MTrk" + struct.pack(">I", len(data)) + data
    hdr = b"MThd" + struct.pack(">IHHH", 6, 1, len(tracks), tpq)
    open(path, "wb").write(hdr + chunks)

if __name__ == "__main__":
    a = sys.argv
    if len(a) < 2:
        print("usage: python mid2glsl.py in.mid [out.glsl] "
              "[--bpm N] [--mode grains|macro|buffer|player] [--no-reverb]")
        sys.exit(1)
    inp  = a[1]
    out  = a[2] if len(a) > 2 and not a[2].startswith("--") else inp.rsplit(".", 1)[0] + ".glsl"
    bpm  = float(a[a.index("--bpm")+1])  if "--bpm"  in a else None
    mode = a[a.index("--mode")+1]        if "--mode" in a else "player"
    reverb = "--no-reverb" not in a              # reverb ON by default; --no-reverb disables
    tpq, tempo, tracks = parse_midi(inp)
    glsl = build_shader(tpq, tempo, tracks, bpm, mode)
    if not reverb:                               # --no-reverb forces the comb reverb off
        glsl = "#define USE_REVERB 0\n" + glsl
    open(out, "w").write(glsl)
    nn = sum(len(t) for t in tracks)
    print(f"{inp}: {len(tracks)} tracks, {nn} notes -> {out} ({mode}{', +reverb' if reverb else ', no-reverb'})")

# ============================================================ BAND (multi-voice)
BAND_PLAYER = r"""
// ---- multi-voice band player -------------------------------------
#define TAU 6.28318530718
float NoteToHz(int n){ return 440.0*exp2((float(n)-69.0)/12.0); }
uint  onTick(uint i){ return midiOM(i)&0xFFFFu; }
uint  meta16(uint i){ return midiOM(i)>>16; }
uint  durTick(uint i){ uint w=midiDur(i>>1u); return ((i&1u)==0u)?(w&0xFFFFu):(w>>16); }
int   metaNote(uint m){ return MIDI_NOTE_MIN+int(m&0x7Fu); }
float metaVel(uint m){ return float((m>>7)&63u)/63.0; }
uint  metaInstr(uint m){ return (m>>13)&7u; }

float nse(float x){ return fract(sin(x*45.233)*43758.5453)*2.0-1.0; }
float fbsin(float p,float fb){ float y=sin(p); y=sin(p+fb*y); y=sin(p+fb*y); return y; }

// ── master soft-knee limiter (ported 1:1 from MOD2GLSL's mod_player.py) ──
// T=0.85 knee: bit-perfect below it; the summed voices approach 1.0 smoothly
// instead of saturating from the first sample like the old always-on tanh.
vec2 softLimit(vec2 x){
    const float T=0.85, HEAD=1.0-T;
    vec2 ax=abs(x), over=max(ax-T,vec2(0.0));
    return sign(x)*(min(ax,vec2(T)) + HEAD*over/(over+HEAD));
}

float vLead(float f,float a,float vel){
    float ph=TAU*f*a;
    float I=(1.0+2.4*vel)*exp2(-a*3.5)+0.6;
    float m=I*fbsin(ph,0.5);
    float dec=0.5+0.5*exp2(-a*0.9);
    return (sin(ph+m)+sin(ph*1.004+m))*0.5*dec;
}
float vBass(float f,float a,float vel){
    float cut=3.0+11.0*exp2(-a*6.0);            // envelope-swept harmonic cutoff
    float s=0.0;
    for(int h=1;h<=10;h++){ float hh=float(h); if(f*hh>15000.0) break;
        s += (1.0/hh)*exp(-0.07*max(hh-cut,0.0))*sin(TAU*f*hh*a); }
    return tanh(s*1.6)*0.6 + sin(TAU*f*a)*0.6;  // + clean sub
}
float vKick(float a){
    float ph=TAU*(45.0*a + 4.328*(1.0-exp2(-30.0*a)));   // integrated pitch sweep
    float body=sin(ph)*exp2(-a*7.0);
    float click=nse(floor(a*45000.0))*exp2(-a*320.0)*0.5;
    return tanh((body+click)*1.7);
}
float vSnare(float a){
    float tone=sin(TAU*185.0*a)*exp2(-a*26.0)*0.4;
    float noise=nse(floor(a*44100.0))*exp2(-a*22.0);
    return tanh((tone+noise)*1.3)*0.85;
}
float vHat(float a){
    float n=nse(floor(a*90000.0)) - nse(floor(a*90000.0)-1.0);  // crude HP
    return n*exp2(-a*55.0)*0.6;
}

vec2 mainSound(int samp, float timeNow){
    float SR=MIDI_SAMPLE_RATE, qSec=float(MIDI_TIME_Q_SAMPLES)/SR;
    float tPhase=float(samp)/SR;
    float songLen=float(MIDI_END_TICK)*qSec;
    float tEvent=mod(tPhase, songLen);
    uint T=uint(floor(tEvent/qSec+0.5)); T=min(T,MIDI_END_TICK-1u);
    uint b=T>>MIDI_BLOCK_SHIFT_TICKS; if(b>=MIDI_BLOCK_COUNT) return vec2(0.0);
    uint padT=uint(1.0/qSec+0.5);
    float L=0.0,R=0.0;
    for(uint j=0u;j<(samp<0 ? 99999u : MIDI_LOOKBACK_BLOCKS);j++){  // de-unroll (see brass template): runtime-opaque bound stops ANGLE unrolling the note scan MIDI_LOOKBACK_BLOCKS×
        if(b<j) break;
        uint bi=b-j, sc=midiSC(bi), start=sc&0xFFFFu, count=sc>>16;
        for(uint k=0u;k<count;k++){
            uint si=start+k; if(si>=MIDI_SEG_COUNT) break;
            uint onT=onTick(si); if(T<onT) continue;
            uint dT=durTick(si), offT=onT+dT;
            if(T>offT+padT) continue;
            uint m=meta16(si); int nn=metaNote(m); float vel=metaVel(m); uint ins=metaInstr(m);
            float onSec=float(onT)*qSec, offSec=float(offT)*qSec;
            float ageOn=max(0.0,tEvent-onSec);
            float held=float(dT)*qSec;
            float ageOff=(tEvent>offSec)?(tEvent-offSec):0.0;
            float f=NoteToHz(nn), s=0.0, pan=0.0, gate=1.0;
            if(ins<=1u){ // melodic: gated
                gate=(tEvent<offSec)?clamp(ageOn/0.01,0.0,1.0)
                                    :exp(-ageOff/0.16)*clamp(held/0.01,0.0,1.0);
                if(gate<0.0005) continue;
            }
            if(ins==0u){ s=vLead(f,ageOn,vel)*gate*vel; pan=clamp((float(nn)-68.0)/22.0,-1.0,1.0)*0.42; }
            else if(ins==1u){ s=vBass(f,ageOn,vel)*gate*vel*0.95; }
            else if(ins==2u){ s=vKick(ageOn)*vel*1.15; }
            else if(ins==3u){ s=vSnare(ageOn)*vel*0.8; pan=0.08; }
            else { s=vHat(ageOn)*vel*0.5; pan=0.32; }
            L+=s*(0.5-pan*0.5); R+=s*(0.5+pan*0.5);
        }
    }
    vec2 lr=softLimit(vec2(L,R)*0.5);   // was tanh(x*0.5): same small-signal level, but transparent below the 0.85 knee
    return lr*smoothstep(0.0,0.4,tPhase);
}
"""

def build_band(notes, Q=256, shift=6, pad_sec=1.0, sr=44100.0):
    # notes: list of (start_s, dur_s, midi, vel127, instr 0..4)
    qSec=Q/sr; c16=lambda x:min(int(x),0xFFFF)
    ev=[]
    for (s,dur,midi,vel,instr) in notes:
        ev.append((round(s/qSec), max(1,round(min(dur,4.0)/qSec)), int(midi), int(vel), int(instr)))
    ev.sort(key=lambda e:e[0])
    N=len(ev); note_min=min(e[2] for e in ev); blk=1<<shift
    end_tick=c16(max(o+d for o,d,_,_,_ in ev)+1); nblocks=(end_tick+blk-1)//blk
    OM=[]; DUR=[]
    for onT,dT,midi,vel,instr in ev:
        vel6=max(0,min(63,round(vel/127*63)))
        meta=((midi-note_min)&0x7F)|((vel6&0x3F)<<7)|((instr&0x7)<<13)
        OM.append(c16(onT)|(meta<<16)); DUR.append(c16(dT))
    if len(DUR)%2: DUR.append(0)
    DURW=[DUR[i]|(DUR[i+1]<<16) for i in range(0,len(DUR),2)]
    SC=[]; idx=0
    for bb in range(nblocks):
        st=idx; cnt=0
        while idx<N and (ev[idx][0]>>shift)==bb: idx+=1; cnt+=1
        SC.append((st&0xFFFF)|(min(cnt,0xFFFF)<<16))
    maxdur=max(d for _,d,_,_,_ in ev); pad=round(pad_sec/qSec)
    lookback=(maxdur+pad)//blk+2
    defs="\n".join(["// paste whole file into the Sound tab",
        "#define MIDI_SAMPLE_RATE 44100.0",f"#define MIDI_TIME_Q_SAMPLES {Q}",
        f"#define MIDI_END_TICK {end_tick}u",f"#define MIDI_BLOCK_SHIFT_TICKS {shift}u",
        f"#define MIDI_BLOCK_COUNT {nblocks}u",f"#define MIDI_SEG_COUNT {N}u",
        f"#define MIDI_LOOKBACK_BLOCKS {lookback}u",f"#define MIDI_NOTE_MIN {note_min}",""])
    return (defs+"\n"+emit_sharded("midiOM",OM)+"\n\n"+emit_sharded("midiDur",DURW)
            +"\n\n"+emit_sharded("midiSC",SC)+"\n"+BAND_PLAYER)
